# src/default_config.toml
db_url = "../db/bkmr.db"

# Available FZF options:
#   --height 50%     Set the height of the finder
#   --reverse        Display results in reverse order
#   --show-tags      Show tags in the display
#   --no-url         Hide URLs in the display
#   --no-action      Hide default actions in the display
[fzf_opts]
height = "50%"
reverse = false
show_tags = false
no_url = false
show_action = true